### PR TITLE
logo upload & readme update

### PR DESCRIPTION
**Pull request by Tobaloidee**

### CODE REVIEW

**Comment by itzmeanjan** [comment]
Hei @Tobaloidee, Merging done :smile:

**Comment by Tobaloidee** [comment]
Thanks a lot! If you are interested in Me designing logos for your other projects I will be gladly doing it..

**Comment by itzmeanjan** [comment]
Hei @Tobaloidee, I was thinking about that. I'll let you know as soon as I complete at least 50% of my work on a project. 

Thanks :heart:

**Comment by Tobaloidee** [comment]
Okay! Just mention me and i will be there..👍😃

**Pull request merged**
